# Generated by Django 3.1.7 on 2021-04-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mins_read',
            field=models.CharField(default=3, max_length=3),
        ),
    ]
